### ISSUE TITLE
[FEATURE] Handling of failed transformation file creation

### ISSUE THREAD

**Issue by airnst** [gfbio/data-transformation-service#25]
#### Description
In the _transform_ service, a `$transformation_file` is created. For particular reasons, such as if no valid/published version is available, the creation may fail. Currently, the DTS only returns a blank web page, which should be replaced by a corresponding error message and code.

#### Open questions
1. What else could cause a failed file creation?

#### Files
index.php

#### Tasks
- [x] Identify other reasons for a failed file creation.
- [x] Implement the described solution.
- [x] Test the implementation.
