### ISSUE TITLE
[FEATURE] Add file size checking

### ISSUE THREAD

**Issue by airnst** [gfbio/data-transformation-service#4]
#### Description
Uploaded files can be arbitrarily large which can pose a security issue. For this reason, the size of a file to be uploaded to the service must be checked in _index.php_ and whether its size is permitted. If it is larger than the allowed size, the client must be informed by a corresponding error message.

#### Open questions
1. From what upper size threshold should upload files be rejected?

#### Files
- [index.php](https://github.com/gfbio/data-transformation-service/blob/main/api/index.php)

#### Tasks
- [x] Discuss a fixed maximum size.
- [x] Implement a file size check.
- [x] Implementation of an error message in case the file is too large.

**Comment by airnst** [comment]
Selected 100MB as initial input file size.
