### ISSUE TITLE
[FEATURE] Delete old results

### ISSUE THREAD

**Issue by airnst** [gfbio/data-transformation-service#8]
#### Description
Results are stored in a folder that is named after a randomly generated job ID and contains input, output and job files. In order to save storage, these folders must be deleted automatically after a previously specified amount of time. 

#### Open questions
1. After what period of time should the results best be deleted?

#### Files

- [index.php](https://github.com/gfbio/data-transformation-service/blob/main/api/index.php)

#### Tasks
- [x] Discuss open questions.
- [x] Implement a delete routine.
- [x] Automate the delete routine.
- [x] Test deletion of old results.

**Comment by airnst** [comment]
Question 1: According to the documentation, results should be retained for 7 days.

**Comment by DavidFichtmueller** [comment]
I have added a command to the crontab to take care of the automation. For now it is set to 30 days, to be adjusted later, after the testing period.
`46 4    * * *   root    find /var/www/dts/api/results/* -type d -daystart -mtime +30 -exec rm -r {} +`

**Comment by airnst** [comment]
Results are never older than 30 days. Test passed. Closed.
